### ISSUE TITLE
Duplicate notifications

### ISSUE THREAD

**Issue by anon-real** [ergo-auction-house/frontend#12]
<img width="543" alt="Screenshot 2023-03-28 at 5 54 36 PM" src="https://user-images.githubusercontent.com/68861503/228398995-8855030d-7540-43c6-b506-593690b4be80.png">

**Comment by anon-real** [comment]
<img width="1013" alt="Screenshot 2023-03-28 at 5 56 05 PM" src="https://user-images.githubusercontent.com/68861503/228399117-283353f4-0654-4b4c-88c6-66ea6212a6ee.png">
Also activities.

**Comment by 11001101110101110001111010111110101** [comment]
> <img alt="Screenshot 2023-03-28 at 5 54 36 PM" width="543" src="https://user-images.githubusercontent.com/68861503/228398995-8855030d-7540-43c6-b506-593690b4be80.png">

this problem has been fixed.

**Comment by 11001101110101110001111010111110101** [comment]
This issue has been fixed. Please check it right now.

**Comment by Zimulakra** [comment]
I'm still seeing a duplicate notification on my end.

<img width="944" alt="double" src="https://user-images.githubusercontent.com/129136234/228905769-dc6e1bbe-a2f5-40ef-b050-674df549d218.png">

**Comment by anon-real** [comment]
I believe this has been resolved. Closing for now. @Zimulakra please report if you see this again.
