### ISSUE TITLE
Error listing items

### ISSUE THREAD

**Issue by ladopixel** [ergo-auction-house/frontend#40]
I don't know if this bug is already covered, but I just realized it.

Once I load an artist's profile I find it impossible to re-list my items. 
I have to forcibly reload the page for my items to load.

The nfts that do not appear are mine, they are from the previous artist

https://user-images.githubusercontent.com/1231955/229751701-695f0c7e-b809-4b01-b172-83ae5bfe94ed.mov

**Comment by ladopixel** [comment]
I think it does not update the component properly.
Reload the page completely if ready successfully.

**Comment by Therisaa** [comment]
Yes, the page didn't update the items on the page. I fixed this bug. It will update the items every time the user page changes.

**Comment by ladopixel** [comment]
It still does not reload my items correctly. I have to force reloading the page completely.

https://user-images.githubusercontent.com/1231955/230146166-ca0f4396-6288-46e7-a0ab-62c9bad4b4c2.mov

**Comment by anon-real** [comment]
@ladopixel are still getting this? Try force refreshing the website (ctrl+shift+R) to see if it helps.

**Comment by ladopixel** [comment]
@anon-real after restarting ignoring cache (Shift + CMD + r) it still does the same thing

https://user-images.githubusercontent.com/1231955/230153315-5eaaece7-3e8d-408d-a31c-cbd4223e79bf.mov

**Comment by anon-real** [comment]
@Therisaa it still has some issues which may be related to this.
Try being in your owned artworks tab and from the profile dropdown select listings. It doesn't work.
