### ISSUE TITLE
Invalid transaction 

### ISSUE THREAD

**Issue by ErgClay** [ergo-auction-house/frontend#66]
Everytime I tried to list any NFT always said after loading Invalid transaction  !!!? how to solve this !!

**Comment by anon-real** [comment]
This is resolved

**Comment by HelixEvo** [comment]
This is still happening.

On Chrome trying to list multiple or single. Does not pop up wallet, just site says "Invalid Transaction"

This is from some items that were imported in from SH collection.
